---

- hosts: k3s_cluster
  gather_facts: True
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspbian
    - role: ubuntu

- hosts: master
  gather_facts: True
  become: yes
  roles:
    - k3s/master
    - andrewrothstein.kubernetes-helm
    - helm
    - redis
    - traefik2

- hosts: node
  gather_facts: True
  become: yes
  roles:
    - role: k3s/node
